# Generated by Django 2.1.5 on 2019-01-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(default=9, verbose_name='Tax number'),
            preserve_default=False,
        ),
    ]
