# Generated by Django 2.1.5 on 2019-01-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0002_company_tax_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(blank=True,null=True, verbose_name='Tax number'),
        ),
    ]
