# Generated by Django 2.1.5 on 2019-01-06 22:21
import random

from django.db import migrations

def gen_tax_number(apps,schema_editor):
    MyModel = apps.get_model("beers","Company")
    for row in MyModel.objects.all():
        row.tax_number = random.randint(1,1000)
        row.save(update_fields=["tax_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0003_auto_20190106_2320'),
    ]

    operations = [
        migrations.RunPython(gen_tax_number,reverse_code=migrations.RunPython.noop),
    ]
