# Generated by Django 2.1.5 on 2019-01-06 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0004_auto_20190106_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(unique=True, verbose_name='Tax number'),
        ),
    ]
