# Generated by Django 2.1.5 on 2019-01-09 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0006_auto_20190109_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beer',
            options={'ordering': ['created_at'], 'verbose_name': 'Beer', 'verbose_name_plural': 'Beers'},
        ),
    ]
