# Generated by Django 2.1.5 on 2019-01-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0009_receta'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='pdf',
            field=models.FileField(default=False, upload_to='documents/'),
        ),
    ]
